version: '3.9'

services:
  flask:
    build: .
    volumes:
      - ./data:/cogmood_backend/data
      - ./metadata:/cogmood_backend/metadata
    ports:
      - "8000:8000"
    expose:
      - "8000"
    mem_limit: "3g"
    cpus: "4"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl_nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cogmoodtest.crt:/etc/ssl/certs/cogmoodtest.crt
      - ./cogmoodtest.key:/etc/ssl/private/cogmoodtest.key
      - ./cogmoodtest_dhparam.pem:/etc/nginx/cogmoodtest_dhparam.pem
      - ./app/static:/static
    depends_on:
      - flask
    mem_limit: "3g"
    cpus: "4"

  util:
    build: .
    volumes:
      - ./data:/cogmood_backend/data:ro
      - ./metadata:/cogmood_backend/metadata:ro
    network_mode: none
    command: ["ls"]
