version: '3.9'

services:
  flask:
    build: .
    volumes:
      - ./data:/cogmood_backend/data
      - ./metadata:/cogmood_backend/metadata
    ports:
      - "8000:8000"
    expose:
      - "8000"
    mem_limit: "3g"
    cpus: "4"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/static
    depends_on:
      - flask
    mem_limit: "3g"
    cpus: "4"

